name: Secret Scan

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run secret scan
        run: |
          node scripts/scan-secrets.mjs || (echo "Secret scan failed. Review potential leaks above." && exit 1)
